# main
GET http://localhost:8080/

###
# 유저의 친구목록 조회
GET http://localhost:8080/api/friends/list/

Content-Type: application/json

{
    "My_id": "tmp1@yonsei.ac.kr",
}

###
# 친구 검색
GET http://localhost:8080/api/friends/search

Content-Type: application/json

{
    "My_id": "tmp1@yonsei.ac.kr",
    "Friend_name" : "yonsei2"
}

###
# post 친구 추가
POST http://localhost:8080/api/friends/add

Content-Type: application/json

{
    "My_id": "tmp1@yonsei.ac.kr",
    "Friend_id": "tmp2@yonsei.ac.kr"
}

###

# 친구관계 상태 변경
POST http://localhost:8080/api/friends/alter

Content-Type: application/json

{
    "My_id": "tmp1@yonsei.ac.kr",
    "Friend_id": "tmp2@yonsei.ac.kr",
    "f_state" : "1"
}

###
# 특정 친구관계 제거
POST http://localhost:8080/api/friends/delete

Content-Type: application/json

{
    "My_id": "tmp1@yonsei.ac.kr",
    "Friend_id": "tmp2@yonsei.ac.kr",
}

#상태메시지 입력
POST http://localhost:8080/api/myinfo/userStMsg

Content-Type: application/json

{
    "My_id": "tmp1@yonsei.ac.kr",
    "statusMsg": "hello",
}

#현재 위치 업데이트
POST http://localhost:8080/api/myinfo/locInfo

Content-Type: application/json

{
    "my_id_loc": "tmp1@yonsei.ac.kr",
    "lat": "28.304000",
    "long": "120.334400",
    "bd_name": "building",
    "f_num": "5",
    "ssid": "building5A",
    "ip": "125.00.1.",
}

#로그아웃
POST http://localhost:8080/api/myinfo/signOut/

Content-Type: application/json
{
    "id": "tmp1@yonsei.ac.kr",
}

#회원탈퇴
POST http://localhost:8080/api/myinfo/delAccount/

Content-Type: application/json

{
    "delId": "tmp1@yonsei.ac.kr",
    "delPw": "123",
}

#주변 목록
GET http://localhost:8080/api/location/place

Content-Type: application/json

{
    "place_userID" = "tmp1@yonsei.ac.kr",
}


#주변 - SSID 누르고 채팅 목록
GET http://localhost:8080/api/location/SSID

Content-Type: application/json
{
    "userID" = "tmp1@yonsei.ac.kr",
    "this_SSID" = "def1A",
}

#내 근처 찾기
GET http://localhost:8080/api/location/nearby

Content-Type: application/json
{
    "near_userID" = "tmp1@yonsei.ac.kr",
}

#위치 추가하기
POST http://localhost:8080/api/location/newplace

Content-Type: application/json

{
    "new_userID": "tmp1@yonsei.ac.kr",
    "new_lat": "23.334400",
    "new_long": "120.335500",
    "new_bd_name": "newbd",
    "new_f_num": "3",
    "new_ssid": "newbd3A",
    "new_ip": "126.00.1.",
}
